// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ6Zmjq1OMqO6tL2NW6O_ZsosyNi610kg',
    appId: '1:253852535559:web:283391698a9668aeeed3a2',
    messagingSenderId: '253852535559',
    projectId: 'natureview2-4cc1a',
    authDomain: 'natureview2-4cc1a.firebaseapp.com',
    storageBucket: 'natureview2-4cc1a.appspot.com',
    measurementId: 'G-NPSQH4KVCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByv_9wasA8S-IOts5TGuluADDZZS8TTNw',
    appId: '1:253852535559:android:b8b6c250475ccaf7eed3a2',
    messagingSenderId: '253852535559',
    projectId: 'natureview2-4cc1a',
    storageBucket: 'natureview2-4cc1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkyVLuYMF_dM6Mgq6IvSxZe2-ztpEQhFk',
    appId: '1:253852535559:ios:685449ad83b9f8b6eed3a2',
    messagingSenderId: '253852535559',
    projectId: 'natureview2-4cc1a',
    storageBucket: 'natureview2-4cc1a.appspot.com',
    iosBundleId: 'com.example.natureview2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkyVLuYMF_dM6Mgq6IvSxZe2-ztpEQhFk',
    appId: '1:253852535559:ios:a0bb7079adf237f1eed3a2',
    messagingSenderId: '253852535559',
    projectId: 'natureview2-4cc1a',
    storageBucket: 'natureview2-4cc1a.appspot.com',
    iosBundleId: 'com.example.natureview2.RunnerTests',
  );
}
